//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blog_akademiazdrowia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public Articles()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public int ArticleId { get; set; }
        public string LayoutType { get; set; }
        public string Category { get; set; }
        public string Title { get; set; }
        public string ShortContent { get; set; }
        public string Content { get; set; }
        public string ImgPath { get; set; }
        public string ImgMiniPath { get; set; }
        public string Tags { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
